nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  '@graphql-cli/introspect@*':
    dependencies:
      '@graphql-inspector/graphql-cli-common': '*'
  '@graphql-cli/common@4':
    dependencies:
      graphql: '^15'
  '@graphql-cli/init@4.1.0':
    dependencies:
      graphql-config: 3.0.3
      yargs: 16.0.3
  '@graphql-cli/introspect@2.1.0':
    dependencies:
      graphql-config: 3.0.3
      yargs: ^15
  '@graphql-inspector/graphql-cli-common@2.9.0':
    dependencies:
      graphql: 15.3.0
  '@graphql-inspector/introspect-command@2.1.0':
    dependencies:
      '@graphql-inspector/config': 2.1.0
      '@graphql-inspector/loaders': 2.1.0
      '@graphql-tools/utils': '^6'
      yargs: 15.3.1
  'graphql-cli@4.1.0':
    dependencies:
      graphql: '15'
  'graphql-yoga@3.0.0-next.10':
    dependencies:
      '@types/node': '^18'
